higlass/server.py
setup.py

* Removed `allow_user` option which wasn't necessary.
* Also fixed slugid dependency.

Fix FUSE runtime error

---

Makefile
higlass/client.py
requirements-dev.txt
requirements.txt

Dev
* Pin dependencies on `jupyterlab` and `ipywidgets`. Currently, custom widgets fail in jlab 1.0 and also break if ipywidgets isn't just right.
* Update makefile
Client
* Deep copy options dicts passed to `Track()`
* Expose `viewconf.views` as a list using a property descriptor
Make `Track` objects more robust and `View`s more easily accessible from `ViewConf`s.

Minor changes

---

higlass/__init__.py

Top level exports

---

notebooks/Examples.ipynb

Need to create a Tileset from the uuid, not just give the uuid to Track.

Fix example 1

---

.github/PULL_REQUEST_TEMPLATE.md
higlass/__init__.py
higlass/client.py
higlass/tilesets.py
higlass/viewer.py
setup.py
test/higlass_test.py
test/tilesets_test.py

Ran black on the entire code base

---

CHANGELOG.md
js/package.json

Bump higlass version

---

CHANGELOG.md
higlass/tilesets.py

> What was changed in this pull request?
Added a tileset constructor for multivec
> Why is it necessary?
To view multivecs

Add constructor for multivec tilesets

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
docs/getting_started.rst
higlass/viewer.py
notebooks/Examples.ipynb

- Added a short snippet about how to use when Juypter is running on a remote server
Fixes #___

Added docs describing how to run on a remote server

---

docs/examples.rst
higlass/client.py
higlass/viewer.py
notebooks/Examples.ipynb

- [More] documentation on zoom and location syncs in the API
- Because the only way to find out how to use this feature was by looking at the source code
Fixes #___

Zoom / location sync documentation

---

docs/getting_started.rst
higlass/__init__.py

- Added a section on how to create a viewconf without a viewer
Fixes #___

Update docs with an example of how to create a viewconf

---

js/package.json
requirements-dev.txt
requirements.txt

Support Jupyterlab 3
Fixes #85
https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#jupyterlab-2-x-to-3-x
https://github.com/keplergl/kepler.gl/issues/1390#issuecomment-856176900

support jupyterlab 3

---

.github/workflows/ci.yml
.gitignore

chore: touch up release workflow

---

README.md

chore: update readme and link to docs

---

README.md

docs: add note about versioning

---

docs/getting_started.rst

docs: Fix numpy example

---

.github/PULL_REQUEST_TEMPLATE.md

Remove legacy checklist steps from PR template

---

src/higlass/_display.py
src/higlass/_widget.py
src/higlass/widget.js

Upgrade higlass front end to v1.13

---

pyproject.toml
uv.lock

Remove legacy `HiGlassServer` dependencies

---

.devcontainer/devcontainer.json
.github/PULL_REQUEST_TEMPLATE.md
.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/docs.yml
README.md
deno.json
docs/README.md
docs/_templates/layout.html
docs/higlass_theme/navigation.html
docs/higlass_theme/static/higlass.css

Formats non-python files `deno fmt`.
Fixes #___

chore: Use consistent formatting for configuration

---

src/higlass/__init__.py
src/higlass/server.py

Fixes #___
- Prefer using prefixes like `fix:` or `feat:` to help organize auto-generated
notes.

feat: Add stub `higlass.server` with deprecation warnings

---

src/higlass/widget.js

- Replace Jupyter server tile sources in combined tracks
- Without this the child tracks of combined tracks aren't able to use the jupyter comms based tile server
Fixes #___
- Prefer using prefixes like `fix:` or `feat:` to help organize auto-generated
notes.

fix:  Resolve jupyter server tile sources in combined tracks
