- higlass/client.py
- higlass/server.py
- higlass/tilesets.py
- notebooks/Examples.ipynb
- requirements.txt
This PR creates the `register_url` endpoint in `higlass.server`. With this endpoint, one need not register tilesets before viewing them in the client.
See also: https://github.com/higlass/higlass/pull/427
> Add the register_url endpoint

- README.md
- environment.yml
- examples/simple-example.ipynb
- higlass/__init__.py
- higlass/client.py
- higlass/server.py
- higlass/tilesets.py
- higlass/widgets.py
- js/README.md
- js/lib/embed.js
- js/lib/extension.js
- js/lib/higlass-jupyter.js
- js/lib/higlass-python.js
- js/lib/index.js
- js/lib/labplugin.js
- js/package.json
- notebooks/Examples.ipynb
- requirements.txt
Rename the `jupyter-higlass` JavaScript files to `higlass-jupyter` to be consistent with the package name.
Also, right now one cannot install the notebook nor the lab extension because of the name clash and because the JS package isn't actually published on npm.
> Rename to higlass-python for consistency

- higlass/server.py
That option doesn't exist for umount which leads to the directory not being unmounted which leads a RunTimeError when trying to mount it.
Fixes #___
> Don't use -l option with umount

- CHANGELOG.md
- higlass/tilesets.py
- test/tilesets_test.py
Added a convenience function for loading 2d labelled points from a pandas dataframe.
To avoid the much longer method of declaring a tileset info and tile loader.
Fixes #___
> 2d labelled points convenience function

- CHANGELOG.md
- higlass/client.py
> What was changed in this pull request?
Support multiple overlays and allow to set the `uid` and `type` options manually
> Why is it necessary?
Previously all overlays used the same uid making it impossible to have two differently styled overlays.
> Support multiple overlays and allow to set the `uid` and `type` options manually

- CHANGELOG.md
- higlass/client.py
- higlass/server.py
- higlass/viewer.py
- js/package.json
> What was changed in this pull request?
1. Added `value_scale_syncs` to `display()` and `ViewConf` to allow setting value scale locks
2. Added `no_fuse` argument to `display()` to allow not to start FUSE
3. Update hglib to `v1.7`
4. Allow setting the server host via the existing host variable
> Why is it necessary?
1. Because I want to use value scale locks
2. Because I don't always need FUSE
3. Because hglib `v1.7` rocks
4. Somehow we hard-coded `0.0.0.0` although we already had a configurable host variable.
> How?
1. Behold:
```python
hans_wurst = hg.Track(uid='hans-wurst', ...)
bock_wurst = hg.Track(uid='bock-wurst', ...)
hg.display(
[hg.View([hans_wurst, bock_wurst])],
valueScaleLocks=[[hans_wurst, bock_wurst]]
valueScaleLocks=[['hans-wurst', 'bock-wurst']]
)
```
If you have more …
> Flekschas/value scale sync, host flexibilify, no fuse

- CHANGELOG.md
- docs/getting_started.rst
- higlass/client.py
- higlass/viewer.py
- test/client_test.py
This PR introduces a new track type for view projections. See the attached change in the docs for an example of how it's used.
This PR also overloads the `+` operator for tracks to create CombinedTracks. So to overlay two tracks, one simple needs to do `track1 + track2`. This same operation can be performed by passing in a list of lists to the View constructor: `View([[track1, track2], track3])`.
The previous method of creating view projections was too cumbersome.
Fixes #___
> Added track type for view projections

- CHANGELOG.md
- docs/getting_started.rst
- higlass/viewer.py
- test/client_test.py
- test/viewer_test.py
This PR provides a simplified way of declaring views in a display by simply passing in a list of tracks.
```
higlass.display([View([Track('top-axis')])])
```
can now be written as:
```
higlass.display([[Track('top-axis')]])
```
Save some typing.
Fixes #___
> Pass in a view as a list of tracks

- higlass/utils.py
- requirements.txt
- test/utils_test.py
Added functions to infer the filetype and datatype of a dataset from its filename. Lifted directly from https://github.com/higlass/higlass-manage/blob/687b40f56fca3c392f401b294828a8c0f9f66c5c/higlass_manage/common.py#L44 and added a test.
Once this is merged, `higlass-manage` can be updated to use the functions here.
To factor out this functionality so that it can be maintained in a common place.
Fixes #___
> Infer filetype and datatype from filename

- CHANGELOG.md
- docs/conf.py
- docs/getting_started.rst
- higlass/client.py
- higlass/viewer.py
- Add the ability to pass in an auth token to be used with the higlass viewer
- Fix some issues with the ViewportProjection and Divided tracks
Using HiGlass with secured data sources requires the ability to pass in authorization information.
Fixes #___
> Auth tokens for viewer

- .travis.yml
- CHANGELOG.md
- docs/getting_started.rst
- higlass/server.py
- higlass/viewer.py
- test/get_test_data.sh
- test/tilesets_test.py
* Implemented `available-chrom-sizes` endpoint
* `Server`'s logging now defaults to an in-memory stream, stored in `server.log`. Providing a `log_file` will create a rotating file handler instead.
* Since the log's name is inherited from the Flask app name, the Server constructor takes a name parameter, which defaults to `higlass` + a short hash. Getting the logger for a given server will then be `logger = logger.getLogger(server.name)`.
Fixes #46
> Log to StringIO by default

- CHANGELOG.md
- docs/getting_started.rst
- higlass/server.py
- higlass/viewer.py
Added support for higlass-python to sit behind a proxy. This is useful for example when running jupyter-notebook on a remote server with a firewall. In this case, the browser can't connect to the higlass backend directly. This PR allows the user to give the base URL to use when accessing the backend.
> Add proxy support

- CHANGELOG.md
- docs/getting_started.rst
- higlass/server.py
- requirements.txt
- test/server_test.py
Passing a host that starts with 'unix://' will make the server bind a unix socket. Host can be a directory, and in this case port will be a filename inside this directory. If host is a directory and port is None, a free 'port' (filename) will be found.
It's useful to ensure no remote access to the higlass daemon (since you need filesystem access) and to limit users from accessing each other’s higlass daemons (via filesystem permissions).
> Add server-side unix sockets support

- CHANGELOG.md
- js/package.json
Bumped react dependency in package.json to version 17.
So that it's compatible with the latest jupyterlab. See https://github.com/higlass/higlass/issues/1045
Fixes #___
> Bumped react version

- requirements.txt
- Bumped matplotlib and pillow versions
- To fix security issues with an older version of pillow
Fixes #___
> Bump matplotlib and pillow versions

- src/higlass/_display.py
- test/test_display.py
- fix: rename of viewconf in HTML repr
- test: add test to ensure viewconf in repr
Fixes HTML renderer that didn't include the view conf after a rename
> fix: insert viewconf into HTML repr template

- src/higlass/_display.py
- src/higlass/api.py
Correctly serializes a `hg.Viewconf` as a `dict` for custom renderers.
Previously custom renderers would need to handle JSON.
Fixes #___
> fix: serialize hg.Viewconf as dict

- src/higlass/_scale.py
- test/test_scale.py
A "partition scale" object to map a composite genomic coordinate system to a partition of its chromosomes into sequential bins.
To simplify the harmonization of the tile partition of HiGlass's scene space at a given zoom level to the often dissimilar partition of the genome used by a data source.
> Add partition scale class

- .github/workflows/ci.yml
- README.md
Changed `master` to `main`. There is a "migration" prompt if you've already cloned the repo:
New default branch for git/GitHub. More consistency with `higlass-schema`/ `higlass-widget`.
Fixes #___
> chore: rename primary branch from master -> main

- .github/workflows/ci.yml
- docs/conf.py
- pyproject.toml
- src/higlass/__init__.py
- src/higlass/_display.py
- test/test_api.py
- test/test_display.py
- test/test_scale.py
- test/test_utils.py
Adds a context manager to `higlass._display.RendererRegistry`, which allows for temporarily enabling a renderer with a context manager.
```python
with hg.renderers.enable("custom") as custom_render:
custom_render(...)
assert hg.renderers.active == "default"
```
I think this will be useful for creating a separate (Jupyter-less) renderer for higlass-python, allowing for opening through a script (addressing #95):
For example, a simple script example:
```python
import higlass as hg
def open_browser(conf)
with hg.renderers.enable("html") as render:
html = render(conf.dict())
encoded = urllib.parse.quote(html)
webbrowser.open("data:text/html," + encoded)
if __name__ == "__main__":
ts = hg.cooler("../data/dataset.mcool")
track = ts.track("heatmap")
view = …
```
> feat: temporarily enable a renderer

- .github/workflows/ci.yml
- src/higlass/_display.py
Bumps higlass client version in the HTML repr to v1.12.
Fixes rendering issue mentioned in #117
Fixes #___
> feat: bump higlass to v1.12

- .github/workflows/docs_s3.yml
- src/higlass/tilesets.py
Added a workflow to push docs to S3.
When the docs page is pushed to the docs-python.higlass.io bucket, they end up in on http://docs-python.higlass.io
Fixes #___
- [o] Unit tests added or updated
- [o] Update `examples.ipynb` notebook
- [o] Documentation added or updated
- [o] Updated CHANGELOG.md
- [o] Ran `black` on the root directory
> Added a workflow to push docs to S3

- docs/conf.py
- pyproject.toml
- src/higlass/_widget.py
- src/higlass/api.py
- src/higlass/widget.js
- Moves `higlass-widget` implementation to this repo. 
- Pins ruff version so that we avoid CI randomly failing with new linting rules.
> feat: move HiGlassWidget to higlass-python

- CHANGELOG.md
- docs/conf.py
- pyproject.toml
- src/higlass/_widget.py
- src/higlass/api.py
- src/higlass/widget.js
- Pass kwargs to `Viewconf.widget()` so that they can be passed to the widget and extra options can be passed directly to the higlass viewer
Fixes #___
> Pass kwargs to widget

- docs/examples.rst
Add a small docs section on passing in an Authorization header.
Fixes #___
> Added docs on passing in an auth header

- docs/getting_started.rst
This pull request adds an example to get search option on genome wide assembly. Example utilizes dataset of higlass.io
It is necessary because  [hg.Viewconf](https://github.com/higlass/higlass-python/blob/main/src/higlass/api.py#L379C7-L379C15) function and [view.viewconf().json()](https://docs-python.higlass.io/getting_started.html#creating-a-viewconf) have different use cases but have similar alias. 
Along with that, it's very unintuitive to identify usages of view.viewconf() to change viewconfig where we can add/update default arguments for root of viewconfig.
Fixes #___
> Example added for searching using higlass-python

- .github/workflows/ci.yml
Fixes #153
Switches ci to use [Trusted Publishers](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/) for publishing to PyPI.
Still need @pkerpedjiev or @nvictus to configure on PyPI's end for the repo.
> ci: Switch to Trusted Publishers

- pyproject.toml
- uv.lock
Before merging #155 and making a release (v1.2), we should make a patch release of higlass-python pinning an upper bound on higlass-schema to `<0.2.0`.
This way, if pydantic v2 breaks users can easily pin higlass-python `<1.2` and get a resolution.
> Pin higlass-schema version upper bound for <v1.2

- pyproject.toml
- src/higlass/_utils.py
- src/higlass/api.py
- uv.lock
Needed to accommodate the pydantic migration in higlass-schema:
- https://github.com/higlass/higlass-schema/pull/16
Staging, until that PR is merged.
> Migrate to higlass-schema v0.2.0 (pydantic v2)

- src/higlass/_utils.py
Shortens the uids from full v4 to the first 8 characters. We don't need the full uuid to uniquely identify tracks/views, and it makes the view configs easier to read.
> Shorter automatic uids

- src/higlass/_display.py
- src/higlass/widget.js
JupyterLab captures right-click ("contextmenu") events globally, causing
conflicts with HiGlass's custom context menus when interacting with
anywidget.
This update introduces an `addEventListenersTo` function that prevents
"contextmenu" events from propagating beyond the widget bounds.
Additional event types can be easily added to this function in the
future if needed.
https://github.com/user-attachments/assets/123eda52-826b-4cd9-a863-51436a8eb8b5
> feat(widget): Suppress right-click event propagation

- CHANGELOG.md
- src/higlass/_utils.py
- test/test_api.py
Calling the `.domain()` function on a view creates a copy of the view. The current copy method dumps the view model and creates a new one from the view. Because views expect PluginTrack types instead of specific subclasses, the dumped model does not contain the class vars of the subclasses (e.g. PileupTrack). Switching to `deepcopy` preserves the class vars of the subclasses.
Here's the error that occurs in the added test without this change:
```
return pydantic_extra[item]
except KeyError as exc:
>                   raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
E                   AttributeError: 'PluginTrack' object has no attribute 'plugin_url'
```
Fixes #___
> fix: Use deepcopy instead of model_dump to copy view

- docs/higlass_theme/static/higlass.css
Fix docs formatting to go from this:
To this:
This is necessary to keep the docs aesthetically pleasing.
Fixes #___
> docs: Hide overflow in code blocks and scale images

- docs/higlass_theme/static/higlass.css
Make sure the sidebar stays up top in the docs:
Compare that to the current situation at https://docs-python.higlass.io/getting_started.html#creating-a-viewconf where the sidebar is at the bottom.
Fixes #___
> fix: Make sure the sidebar stays up top in the docs on wide screens

- docs/getting_started.rst
- docs/higlass_theme/static/higlass.css
Just some little nits. There are some warnings from Sphinx and the css lets you actually scroll the text when it overflows in y.
- **Fix sphinx warnings**
- **Set `overflow: scroll` for code snippets**
Fixes #___
> docs: fix Sphinx warnings and allow scroll for code snippets 

- examples/JupyterServer.ipynb
- src/higlass/__init__.py
- src/higlass/api.py
- src/higlass/tilesets.py
- test/test_tileset_registery.py
The `register` naming is not very clear, and also the meta-programming
in the previous approach erased type information. By having a shared
based class, implementing a custom tileset is much nicer:
```py
from dataclasses import dataclass
import higlass as hg
from clodius.tiles import cooler
@dataclass
class MyCustomCoolerTileset(hg.Tileset):
path: str
datatype = "matrix"
def tiles(self, tile_ids):
return cooler.tiles(self.path, tile_ids)
def info(self):
return cooler.tileset_info(self.path)
ts = MyCustomCoolerTileset("test.mcool")
hg.view(ts.track())
```
Fixes #___
- Prefer using prefixes like `fix:` or `feat:` to help organize auto-generated
notes.
> Replace `higlass.tilesets.register` with `higlass.Tileset`

- README.md
Fixes #___
- Prefer using prefixes like `fix:` or `feat:` to help organize auto-generated
notes.
> chore: Add dev instructions for JavaScript code

- src/higlass/types.ts
- src/higlass/widget.js
HiGlass's built-in data fetching logic is designed to optimize API calls
by consolidating requests based on time, ID, and server. Our custom
Jupyter data fetcher doesn't include these optimizations.
This PR introduces a `consolidator` helper, which performs a much simpler
form of batching. Since we assume a single server, this function only
batches tile requests that occur within the same animation frame and
submits them together. This helps reduce the number of comms calls, and
at a minimum dedupes requests with the same tile id.
This is the approach taken in [mosaic](https://idl.cs.washington.edu/files/2024-Mosaic-TVCG.pdf): 
> "As multiple queries tend to be issued in tandem (for example upon
initialization), the Coordinator waits one animation frame, collects
incoming queries, and …
> feat(widget): Batch tile requests within an animation frame
